# SOME DESCRIPTIVE TITLE.
# Copyright (C) YEAR THE PACKAGE'S COPYRIGHT HOLDER
# This file is distributed under the same license as the PACKAGE package.
# FIRST AUTHOR <EMAIL@ADDRESS>, YEAR.
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: PACKAGE VERSION\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2025-09-26 20:10+0400\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"Language: \n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=CHARSET\n"
"Content-Transfer-Encoding: 8bit\n"

#: selfprivacy_api/repositories/users/exceptions.py:10
msgid "User not found"
msgstr ""

#: selfprivacy_api/repositories/users/exceptions.py:19
msgid "User or group not found"
msgstr ""

#: selfprivacy_api/repositories/users/exceptions.py:28
msgid "User is protected and cannot be deleted or modified"
msgstr ""

#: selfprivacy_api/repositories/users/exceptions.py:37
msgid "Username is forbidden"
msgstr ""

#: selfprivacy_api/repositories/users/exceptions.py:46
msgid "User already exists"
msgstr ""

#: selfprivacy_api/repositories/users/exceptions.py:55
msgid "Username must be alphanumeric and start with a letter"
msgstr ""

#: selfprivacy_api/repositories/users/exceptions.py:64
msgid "Username is too long. Must be less than 32 characters"
msgstr ""

#: selfprivacy_api/repositories/users/exceptions.py:73
msgid "Password cannot be empty"
msgstr ""

#: selfprivacy_api/repositories/users/exceptions.py:82
msgid "Invalid configuration, userdata is broken"
msgstr ""

#: selfprivacy_api/repositories/users/exceptions.py:91
msgid "The Kanidm response does not contain a password reset link."
msgstr ""

#: selfprivacy_api/repositories/users/exceptions.py:100
msgid "Display name is too long. Must be less than 16 characters"
msgstr ""

#: selfprivacy_api/repositories/users/exceptions_kanidm.py:25
#, python-format
msgid " Method: %(method)s"
msgstr ""

#: selfprivacy_api/repositories/users/exceptions_kanidm.py:27
#, python-format
msgid " Endpoint: %(endpoint)s"
msgstr ""

#: selfprivacy_api/repositories/users/exceptions_kanidm.py:31
#, python-format
msgid " Error: %(error)s"
msgstr ""

#: selfprivacy_api/repositories/users/exceptions_kanidm.py:41
msgid "Kanidm returned an empty response."
msgstr ""

#: selfprivacy_api/repositories/users/exceptions_kanidm.py:53
#, python-format
msgid "Kanidm returned unknown type response. Response: %(response)s"
msgstr ""

#: selfprivacy_api/repositories/users/exceptions_kanidm.py:56
msgid "Kanidm returned unknown type response."
msgstr ""

#: selfprivacy_api/repositories/users/exceptions_kanidm.py:66
msgid "Kanidm didn't return the admin password."
msgstr ""

#: selfprivacy_api/repositories/users/exceptions_kanidm.py:78
#, python-format
msgid "An error occurred when using Kanidm CLI. Error: %(error)s"
msgstr ""

#: selfprivacy_api/repositories/users/exceptions_kanidm.py:81
msgid "An error occurred when using Kanidm cli"
msgstr ""

#: selfprivacy_api/repositories/users/exceptions_kanidm.py:91
msgid "Failed to get valid Kanidm token."
msgstr ""

#: selfprivacy_api/actions/ssh.py:26
msgid "Key not found"
msgstr ""

#: selfprivacy_api/actions/ssh.py:35
msgid "Key already exists"
msgstr ""

#: selfprivacy_api/actions/ssh.py:45
msgid "Invalid key type. Only ssh-ed25519, ssh-rsa and ecdsa are supported"
msgstr ""

#: selfprivacy_api/actions/users.py:47
msgid "API is using a too old or unfinished user repository"
msgstr ""
